name: Format

on:
  push:
    branches:
      - master
      - main

  pull_request:

jobs:
  shfmt:
    name: Verify formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install shfmt
        uses: mfinelli/setup-shfmt@v3

      - name: Check formatting
        run: |
          shfmt -d .
